### ISSUE TITLE
[Documentation Issue] : docs

### ISSUE THREAD

**Issue by Puskar-Roy2** [Puskar-Roy/create-my-api#11]
### Brief Description 📝

Add Docs

### Select the open-source program you are contributing to

SSOC

### Code of Conduct

- [X] I agree to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by Puskar-Roy** [comment]
Hey @Puskar-Roy2👋! Thanks for raising this issue and demonstrating your interest in contributing to our project!🚀
    We value your engagement and eagerly anticipate your contributions. Should you wish to get involved, please use the /gdsc command to self-assign the issue.
    This issue provides an excellent opportunity for us to enhance our project, and we're excited to have you join us! Please take a moment to review our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) before getting started.
    If you have any questions or need assistance, feel free to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/).❤️

**Comment by Puskar-Roy** [comment]
Hello @Puskar-Roy2! We'd like to inform you that the issue has been resolved and is now closed. We appreciate your understanding and look forward to your continued involvement with our repository!🤗
If you encounter any further issues, please don't hesitate to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/). Thank you for your support!❣️
Happy coding!✨ We hope to see you again soon!❣️
