### ISSUE TITLE
Add contact us form

### ISSUE THREAD

**Issue by meghanakn473** [Puskar-Roy/create-my-api#120]
### Quick Description 🛠️

I want to set up contact us page and a contact us form so that users can reach out when they r facing issues

@Puskar-Roy please assign me this issue with level 2, gssoc-extd, hacktoberfest

### Select the open-source program you're contributing to

GSSOC 2024 EXTD, Hacktoberfest 2024

### Adherence to Code of Conduct

- [X] I adhere to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by Puskar-Roy** [comment]
Hey @meghanakn473👋! Thanks for raising this issue and demonstrating your interest in contributing to our project!🚀
    We value your engagement and eagerly anticipate your contributions. Should you wish to get involved, please use the /assignme command to self-assign the issue.
    This issue provides an excellent opportunity for us to enhance our project, and we're excited to have you join us! Please take a moment to review our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) before getting started.
    If you have any questions or need assistance, feel free to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/).❤️

**Comment by meghanakn473** [comment]
@Puskar-Roy please add the labels level 2, gssoc-extd, hacktoberfest

**Comment by SupriyaGo** [comment]
is this issue still available ? @Puskar-Roy , I can work on it

**Comment by meghanakn473** [comment]
@Puskar-Roy please check i have closed the old pr and maade new pr in dev branch
