### ISSUE TITLE
[Documentation Issue] :  Enhancement Of Contributing.md

### ISSUE THREAD

**Issue by milansamuel609** [Puskar-Roy/create-my-api#132]
### Brief Description 📝

The contributing.md file is not in a structured manner. Also some sections are missing. I can enhance it in a well structured manner with proper details and some additional sections also that will make the contributors easier to contribute. Please can you assign me this task?

Wanted to do the following changes :-

1) Enhance the project structure
2) Add need help with the basics section
3) Add project structure section
4) Add additional method of contributing through GitHub desktop section
5) Add good coding practices section
6) Add the help and support section
7) Add the pull request section
8) Add issue report process section

### Select the open-source program you are contributing to

GSSOC 2024 EXTD, Hacktoberfest 2024

### Code of Conduct

- [X] I agree to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by Puskar-Roy** [comment]
Hey @milansamuel609👋! Thanks for raising this issue and demonstrating your interest in contributing to our project!🚀
    We value your engagement and eagerly anticipate your contributions. Should you wish to get involved, please use the /assignme command to self-assign the issue.
    This issue provides an excellent opportunity for us to enhance our project, and we're excited to have you join us! Please take a moment to review our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) before getting started.
    If you have any questions or need assistance, feel free to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/).❤️

**Comment by milansamuel609** [comment]
> Hey @milansamuel609👋! Thanks for raising this issue and demonstrating your interest in contributing to our project!🚀 We value your engagement and eagerly anticipate your contributions. Should you wish to get involved, please use the /assignme command to self-assign the issue. This issue provides an excellent opportunity for us to enhance our project, and we're excited to have you join us! Please take a moment to review our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) before getting started. If you have any questions or need assistance, feel free to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/).❤️

Thank you for giving me this opportunity. I will surely give my best.

**Comment by Puskar-Roy** [comment]
Hey @milansamuel609, the issue has already been assigned and cannot be assigned to you again. Feel free to work on another issue or create a new one.😥

**Comment by milansamuel609** [comment]
Ok no problem 👍

**Comment by Puskar-Roy** [comment]
Hello @milansamuel609! We'd like to inform you that the issue has been resolved and is now closed. We appreciate your understanding and look forward to your continued involvement with our repository!🤗
If you encounter any further issues, please don't hesitate to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/). Thank you for your support!❣️
Happy coding!✨ We hope to see you again soon!❣️
