### ISSUE TITLE
[ADD API] : Adding feedback section with rating star

### ISSUE THREAD

**Issue by rahulbamnuya** [Puskar-Roy/create-my-api#134]
### API Summary 📝

I would like to add feedback and rating section in website

### Development Approach 🚀

I will create an a button in downward in page when user click i they got pop up form of feedback and after form submit they got good message

### Deployment Status

Yes

### Select the open source program you are contributing to

GSSOC 2024 EXTD, Hacktoberfest 2024

### Code of Conduct

- [X] I adhere to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by Puskar-Roy** [comment]
Hey @rahulbamnuya👋! Thanks for raising this issue and demonstrating your interest in contributing to our project!🚀
    We value your engagement and eagerly anticipate your contributions. Should you wish to get involved, please use the /assignme command to self-assign the issue.
    This issue provides an excellent opportunity for us to enhance our project, and we're excited to have you join us! Please take a moment to review our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) before getting started.
    If you have any questions or need assistance, feel free to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/).❤️

**Comment by Puskar-Roy** [comment]
Hello @rahulbamnuya! We'd like to inform you that the issue has been resolved and is now closed. We appreciate your understanding and look forward to your continued involvement with our repository!🤗
If you encounter any further issues, please don't hesitate to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/). Thank you for your support!❣️
Happy coding!✨ We hope to see you again soon!❣️
