### ISSUE TITLE
[Documentation Issue] : Improve Code Readability and Documentation for TerminalCard Component

### ISSUE THREAD

**Issue by Sumanth077s** [Puskar-Roy/create-my-api#142]
### Brief Description 📝

1 Semantic Issue: Misuse of <div> for decorative circles; should use <span> instead.
2 Inline JSX Expression: Extra whitespace in the JSX expression for the question prompt.
3 Excessive JSX Tags: Multiple <p> tags used for each line of output; can be grouped for cleaner structure.
4 Hardcoded Text: Terminal output is hardcoded, limiting reusability for different commands.
5 Color Contrast: The "bash" label's color lacks contrast against the black background, reducing readability.

### Select the open-source program you are contributing to

GSSOC 2024 EXTD, Hacktoberfest 2024

### Code of Conduct

- [X] I agree to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by Puskar-Roy** [comment]
Hey @Sumanth077s👋! Thanks for raising this issue and demonstrating your interest in contributing to our project!🚀
    We value your engagement and eagerly anticipate your contributions. Should you wish to get involved, please use the /assignme command to self-assign the issue.
    This issue provides an excellent opportunity for us to enhance our project, and we're excited to have you join us! Please take a moment to review our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) before getting started.
    If you have any questions or need assistance, feel free to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/).❤️

**Comment by Puskar-Roy** [comment]
Hello @Sumanth077s! We'd like to inform you that the issue has been resolved and is now closed. We appreciate your understanding and look forward to your continued involvement with our repository!🤗
If you encounter any further issues, please don't hesitate to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/). Thank you for your support!❣️
Happy coding!✨ We hope to see you again soon!❣️
