### ISSUE TITLE
[API Improvement] : Add docker file

### ISSUE THREAD

**Issue by manya1632** [Puskar-Roy/create-my-api#144]
### Quick Description 🛠️

I would like to add a docker file, so that the user who clones this repo can access it locally with a single command 

Checklist
✔️I have read the Contributing Guidelines
✔️I have read the Code Of Conduct
✔️The changes don't break the code

Please assign it to me !!

### Select the open-source program you're contributing to

GSSOC 2024 EXTD, Hacktoberfest 2024

### Adherence to Code of Conduct

- [X] I adhere to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by Puskar-Roy** [comment]
Hey @manya1632👋! Thanks for raising this issue and demonstrating your interest in contributing to our project!🚀
    We value your engagement and eagerly anticipate your contributions. Should you wish to get involved, please use the /assignme command to self-assign the issue.
    This issue provides an excellent opportunity for us to enhance our project, and we're excited to have you join us! Please take a moment to review our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) before getting started.
    If you have any questions or need assistance, feel free to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/).❤️

**Comment by manya1632** [comment]
@Puskar-Roy  please let me know if your website needs a docker file. ?

**Comment by Puskar-Roy** [comment]
@Puskar-Roy make a docker file in root directory, and run the only ```apps/web``` it's a next js web.

**Comment by manya1632** [comment]
Sir I am facing some issue with a command  > [4/6] RUN npm install  --legacy-peer-deps:
91.64 npm notice
91.64 npm notice New minor version of npm available! 10.7.0 -> 10.9.0
91.64 npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.0
91.64 npm notice To update run: npm install -g npm@10.9.0
91.64 npm notice
91.64 npm error code E404
91.64 npm error 404 Not Found - GET https://registry.npmjs.org/@repo%2feslint-config - Not found
91.64 npm error 404
91.64 npm error 404  '@repo/eslint-config@*' is not in this registry.
91.64 npm error 404
91.64 npm error 404 Note that you can also install from a
91.64 npm error 404 tarball, folder, http url, or git url.
91.65
91.65 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-10-26T08_11_56_072Z-debug-0.log
------
Dockerfile:9
--------------------
   7 |     ENV NODE_OPTIONS=--max-old-space-size=2048
   8 |
   9 | >>> RUN npm install  --legacy-peer-deps
  10 |
  11 |     COPY apps/web/ .
--------------------
ERROR: failed to solve: process "/bin/sh -c npm install  --legacy-peer-deps" did not complete successfully: exit code: 1  , can you please tell where i am stuck, i have been trying for a long time

**Comment by Puskar-Roy** [comment]
Hello @manya1632! We'd like to inform you that the issue has been resolved and is now closed. We appreciate your understanding and look forward to your continued involvement with our repository!🤗
If you encounter any further issues, please don't hesitate to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/). Thank you for your support!❣️
Happy coding!✨ We hope to see you again soon!❣️
