### ISSUE TITLE
About section has no padding from the left 

### ISSUE THREAD

**Issue by DarshanchGIT** [Puskar-Roy/create-my-api#28]
![Screenshot_2024_1001_193324.jpg](https://github.com/user-attachments/assets/ae129b1b-2a17-4278-a957-8c617453fc28)

**Comment by Puskar-Roy** [comment]
Hey @DarshanchGIT👋! Thanks for raising this issue and demonstrating your interest in contributing to our project!🚀
    We value your engagement and eagerly anticipate your contributions. Should you wish to get involved, please use the /assignme command to self-assign the issue.
    This issue provides an excellent opportunity for us to enhance our project, and we're excited to have you join us! Please take a moment to review our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) before getting started.
    If you have any questions or need assistance, feel free to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/).❤️

**Comment by DarshanchGIT** [comment]
can you label it. with gssoc and hacktoberfest

**Comment by Puskar-Roy** [comment]
@DarshanchGIT hey did u work on this issue?

**Comment by DarshanchGIT** [comment]
> @DarshanchGIT hey did u work on this issue?
> 

Actually It was alright, my bad !!

**Comment by 29akeshvimt** [comment]
Hey!
May you assign it to me

**Comment by Puskar-Roy** [comment]
@29akeshvimt do want to work in this issue

**Comment by Puskar-Roy** [comment]
Hello @DarshanchGIT! We'd like to inform you that the issue has been resolved and is now closed. We appreciate your understanding and look forward to your continued involvement with our repository!🤗
If you encounter any further issues, please don't hesitate to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/). Thank you for your support!❣️
Happy coding!✨ We hope to see you again soon!❣️
