### ISSUE TITLE
Misalignment of footer 

### ISSUE THREAD

**Issue by adityapandey23** [Puskar-Roy/create-my-api#29]
![image](https://github.com/user-attachments/assets/b074e527-826e-42a1-8f0a-3f99b2244206)

The footer seems to be a bit misaligned. Can you please assign this issue to me so that I start working on it!

**Comment by Puskar-Roy** [comment]
Hey @adityapandey23👋! Thanks for raising this issue and demonstrating your interest in contributing to our project!🚀
    We value your engagement and eagerly anticipate your contributions. Should you wish to get involved, please use the /assignme command to self-assign the issue.
    This issue provides an excellent opportunity for us to enhance our project, and we're excited to have you join us! Please take a moment to review our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) before getting started.
    If you have any questions or need assistance, feel free to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/).❤️

**Comment by adityapandey23** [comment]
Hey @Puskar-Roy, I have raised a pr, you check accordingly. Also just curious, will this contribution be counted in GGSOC-ext ?
Looking forward to make more contribution to this project✨

**Comment by Puskar-Roy** [comment]
@adityapandey23 yes your contribution will be counted as GSSOC-ext and please send pr in dev branch

**Comment by adityapandey23** [comment]
Hey @Puskar-Roy, sorry my bad. I pushed it to dev now. Can you please check now ?

**Comment by Puskar-Roy** [comment]
Hello @adityapandey23! We'd like to inform you that the issue has been resolved and is now closed. We appreciate your understanding and look forward to your continued involvement with our repository!🤗
If you encounter any further issues, please don't hesitate to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/). Thank you for your support!❣️
Happy coding!✨ We hope to see you again soon!❣️
