### ISSUE TITLE
Abnormal file modification

### ISSUE THREAD

**Issue by adityapandey23** [Puskar-Roy/create-my-api#30]
After running `npm install`, in the main-cli, the index.js is modified
![image](https://github.com/user-attachments/assets/914472ec-1746-4776-8cbc-51d643bca0d2)

**Comment by Puskar-Roy** [comment]
Hey @adityapandey23👋! Thanks for raising this issue and demonstrating your interest in contributing to our project!🚀
    We value your engagement and eagerly anticipate your contributions. Should you wish to get involved, please use the /assignme command to self-assign the issue.
    This issue provides an excellent opportunity for us to enhance our project, and we're excited to have you join us! Please take a moment to review our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) before getting started.
    If you have any questions or need assistance, feel free to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/).❤️

**Comment by Puskar-Roy** [comment]
@adityapandey23 can you please explain what's the issue?

**Comment by adityapandey23** [comment]
After cloning the repository, if we install all the dependencies using `npm install`, the file that I mentioned (`index.js` in main-cli folder) automatically get's modified and shows that `M` symbol

**Comment by Puskar-Roy** [comment]
Hello @adityapandey23! We'd like to inform you that the issue has been resolved and is now closed. We appreciate your understanding and look forward to your continued involvement with our repository!🤗
If you encounter any further issues, please don't hesitate to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/). Thank you for your support!❣️
Happy coding!✨ We hope to see you again soon!❣️

**Comment by Puskar-Roy** [comment]
@adityapandey23 ok i see
