### ISSUE TITLE
[WEB Improvement] : The github stars section is disappearing in mobile view

### ISSUE THREAD

**Issue by ShivanshPlays** [Puskar-Roy/create-my-api#34]
### Quick Description 🛠️

https://github.com/user-attachments/assets/5272f23e-c00c-4917-86b1-6ab81091aacf

I am eager to start working on it , could you please assign it to me?

### Select the open-source program you're contributing to

Other

### Adherence to Code of Conduct

- [X] I adhere to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by Puskar-Roy** [comment]
Hey @ShivanshPlays👋! Thanks for raising this issue and demonstrating your interest in contributing to our project!🚀
    We value your engagement and eagerly anticipate your contributions. Should you wish to get involved, please use the /assignme command to self-assign the issue.
    This issue provides an excellent opportunity for us to enhance our project, and we're excited to have you join us! Please take a moment to review our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) before getting started.
    If you have any questions or need assistance, feel free to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/).❤️

**Comment by uzefaqureshi06** [comment]
can you assign this to me I will work on it

**Comment by Puskar-Roy** [comment]
Hey @uzefaqureshi06 I think @ShivanshPlays working on this issue, can please create a new issue and work on it.
