### ISSUE TITLE
[WEB Improvement] : Add Dynamic GitHub Stars Section ⭐

### ISSUE THREAD

**Issue by Puskar-Roy** [Puskar-Roy/create-my-api#35]
### Quick Description 🛠️

Currently all the Github Starts that shown in The Website is Static, make it Dynamic Github Stars
![Screenshot_2024-10-02-07-27-46-066_com android chrome-edit](https://github.com/user-attachments/assets/90f3f335-b4ff-49ac-af26-da1181027e56)

### Select the open-source program you're contributing to

Other

### Adherence to Code of Conduct

- [X] I adhere to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by Puskar-Roy** [comment]
Hey @Puskar-Roy👋! Thanks for raising this issue and demonstrating your interest in contributing to our project!🚀
    We value your engagement and eagerly anticipate your contributions. Should you wish to get involved, please use the /assignme command to self-assign the issue.
    This issue provides an excellent opportunity for us to enhance our project, and we're excited to have you join us! Please take a moment to review our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) before getting started.
    If you have any questions or need assistance, feel free to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/).❤️

**Comment by South-IN** [comment]
Hey! puskar can i work on this issue ?

**Comment by Puskar-Roy** [comment]
@South-IN Sure!

**Comment by South-IN** [comment]
Hey puskar  i needed some help where should i write the issue number in the PR?

**Comment by Puskar-Roy** [comment]
@South-IN So You Can Add Issue Number In Title Of The PR, 
You can follow this format and Replace **Issue Number** and **<issue_no>** with Your Issue Number. 

![IMG_20241002_105652](https://github.com/user-attachments/assets/0bb57999-a062-4239-84ed-58aad73f273c)

**Comment by South-IN** [comment]
ok thank you and where can i find the "rules of when pr will get merged"?

**Comment by Puskar-Roy** [comment]
@South-IN push the code in dev branch, it's just a recommendation that if you want to contribute in some repo at first read the contributing.md.

**Comment by South-IN** [comment]
@Puskar-Roy  i am sorry but i read the contributing.md and couldn't find any mention of merging code to the dev branch that's why I asked where can I find the "rules of when pr will be merged".

**Comment by Puskar-Roy** [comment]
@South-IN are no issues 😃

**Comment by Puskar-Roy** [comment]
Hello @Puskar-Roy! We'd like to inform you that the issue has been resolved and is now closed. We appreciate your understanding and look forward to your continued involvement with our repository!🤗
If you encounter any further issues, please don't hesitate to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/). Thank you for your support!❣️
Happy coding!✨ We hope to see you again soon!❣️
