### ISSUE TITLE
[ADD API] : Rust-ActixWeb-Postgres

### ISSUE THREAD

**Issue by HarshitShukla-dev** [Puskar-Roy/create-my-api#40]
### API Summary 📝

The **Rust-ActixWeb-Postgres API Template** is a production-ready starter template for building high-performance RESTful APIs using the **Actix Web** framework and **PostgreSQL** as the database. This template is designed to provide a solid foundation for backend development in Rust, featuring authentication, database connection pooling, environment variable management, and a clear project structure for scalable and maintainable applications.

Key Features:
- Actix Web for fast and efficient web server capabilities.
- PostgreSQL integration using `deadpool-postgres` for database management.
- Structured project layout to support modular and scalable development.
- Includes routes for user authentication, CRUD operations, and error handling.

Ideal for developers looking to leverage Rust’s performance and reliability to build robust web APIs.

### Development Approach 🚀

The **Rust-ActixWeb-Postgres API Template** was designed with scalability, performance, and maintainability in mind. Here’s an overview of the approach used during the development process:

1. **Project Structure Setup**:
   - Organized the project into modular components to enhance scalability and maintain code cleanliness. Key folders include `routes` (API endpoints), `models` (data structures), `services` (business logic), and `config` (environment and database configuration).

2. **Actix Web Framework**:
   - Actix Web was chosen for its asynchronous and lightweight nature, ensuring high performance under heavy loads. The server is built to handle a range of HTTP methods (GET, POST, PUT, DELETE) with a clear separation of concerns for each route.

3. **PostgreSQL Integration**:
   - Integrated **PostgreSQL** using `deadpool-postgres` for efficient connection pooling and asynchronous database queries. The project ensures database access is handled safely and efficiently across multiple routes.

4. **Authentication & Security**:
   - Implemented basic JWT-based authentication, allowing for secure API requests and token-based access control. This ensures that sensitive routes can only be accessed by authenticated users.

5. **Error Handling & Logging**:
   - Custom error types and a global error handler were implemented to provide meaningful error responses, improving API robustness and ease of debugging. Logging is set up for tracking and monitoring purposes.

6. **Environment Management**:
   - Used the `dotenv` crate to manage environment variables, keeping sensitive configurations (like database credentials and API keys) separated from the codebase for security and flexibility.

By following this approach, the template ensures optimal performance, clean code, and flexibility, making it easy to extend and maintain for future use cases.

### Deployment Status

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I adhere to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### Request
Please assign hacktoberfest, GSSOC-ext and level label to this issue.

**Comment by Puskar-Roy** [comment]
Hey @HarshitShukla-dev👋! Thanks for raising this issue and demonstrating your interest in contributing to our project!🚀
    We value your engagement and eagerly anticipate your contributions. Should you wish to get involved, please use the /assignme command to self-assign the issue.
    This issue provides an excellent opportunity for us to enhance our project, and we're excited to have you join us! Please take a moment to review our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) before getting started.
    If you have any questions or need assistance, feel free to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/).❤️
