### ISSUE TITLE
Adding close button in login page

### ISSUE THREAD

**Issue by Aditijainnn** [Puskar-Roy/create-my-api#54]
### Brief Description 📝

![image](https://github.com/user-attachments/assets/62980d17-1e12-4d43-b205-040b2d06c6c4)
in sign-in page there is no option for going back and closing it so want to add that feature please assign this to me under gssoc ext and hacktoberfest

### Select the open-source program you are contributing to

Other

### Code of Conduct

- [X] I agree to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by Puskar-Roy** [comment]
Hey @Aditijainnn👋! Thanks for raising this issue and demonstrating your interest in contributing to our project!🚀
    We value your engagement and eagerly anticipate your contributions. Should you wish to get involved, please use the /assignme command to self-assign the issue.
    This issue provides an excellent opportunity for us to enhance our project, and we're excited to have you join us! Please take a moment to review our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) before getting started.
    If you have any questions or need assistance, feel free to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/).❤️

**Comment by Puskar-Roy** [comment]
@Aditijainnn can u please explain the issue? 
Like in this project their is no Sign up page 🥲

**Comment by Aditijainnn** [comment]
``

> @Aditijainnn can u please explain the issue? Like in this project their is no Sign up page 🥲

![image](https://github.com/user-attachments/assets/832639e9-7372-4685-8093-749fa0a0d5fc)

**Comment by Puskar-Roy** [comment]
@Aditijainnn actually its the npm official registry so we can change anything here!

**Comment by Aditijainnn** [comment]
> @Aditijainnn actually its the npm official registry so we can change anything here!

ok sorry my bad

**Comment by Puskar-Roy** [comment]
Hello @Aditijainnn! We'd like to inform you that the issue has been resolved and is now closed. We appreciate your understanding and look forward to your continued involvement with our repository!🤗
If you encounter any further issues, please don't hesitate to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/). Thank you for your support!❣️
Happy coding!✨ We hope to see you again soon!❣️
