### ISSUE TITLE
Misbehaving buttons in the herosection

### ISSUE THREAD

**Issue by adityapandey23** [Puskar-Roy/create-my-api#55]
The buttons in the hero section (next navigation, github and npm) only works if we click on the icons not on the button. It's a minor issue I can fix it. If you feel it's worth then assign it to me otherwise we can close this issue.

**Comment by Puskar-Roy** [comment]
Hey @adityapandey23👋! Thanks for raising this issue and demonstrating your interest in contributing to our project!🚀
    We value your engagement and eagerly anticipate your contributions. Should you wish to get involved, please use the /assignme command to self-assign the issue.
    This issue provides an excellent opportunity for us to enhance our project, and we're excited to have you join us! Please take a moment to review our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) before getting started.
    If you have any questions or need assistance, feel free to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/).❤️

**Comment by adityapandey23** [comment]
Hey!
@Puskar-Roy I have fixed the issue please check #56  pr.
Looking forward to contribute more to the repo :)

**Comment by Puskar-Roy** [comment]
@adityapandey23 Thanks :)

**Comment by Puskar-Roy** [comment]
Hello @adityapandey23! We'd like to inform you that the issue has been resolved and is now closed. We appreciate your understanding and look forward to your continued involvement with our repository!🤗
If you encounter any further issues, please don't hesitate to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/). Thank you for your support!❣️
Happy coding!✨ We hope to see you again soon!❣️
