### ISSUE TITLE
[WEB Improvement] :  Improve Mobile Responsiveness and Fix UI Bugs

### ISSUE THREAD

**Issue by Joshna907** [Puskar-Roy/create-my-api#71]
### Quick Description 🛠️

While the website is generally responsive, there are areas that could benefit from further optimization for mobile devices. Some UI elements do not scale correctly, affecting usability on smaller screens.

### Select the open-source program you're contributing to

Other

### Adherence to Code of Conduct

- [X] I adhere to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by Puskar-Roy** [comment]
Hey @Joshna907👋! Thanks for raising this issue and demonstrating your interest in contributing to our project!🚀
    We value your engagement and eagerly anticipate your contributions. Should you wish to get involved, please use the /assignme command to self-assign the issue.
    This issue provides an excellent opportunity for us to enhance our project, and we're excited to have you join us! Please take a moment to review our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) before getting started.
    If you have any questions or need assistance, feel free to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/).❤️

**Comment by Joshna907** [comment]
Done Please do check !!

**Comment by Joshna907** [comment]
@Puskar-Roy

**Comment by Puskar-Roy** [comment]
Hello @Joshna907! We'd like to inform you that the issue has been resolved and is now closed. We appreciate your understanding and look forward to your continued involvement with our repository!🤗
If you encounter any further issues, please don't hesitate to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/). Thank you for your support!❣️
Happy coding!✨ We hope to see you again soon!❣️
