### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by Sourabh782** [Puskar-Roy/create-my-api#74]
### API Summary 📝

The current UI of scrolling is not working properly, its too down and its not visible properly

https://github.com/user-attachments/assets/a5b8a2c5-fe05-4e97-ba95-16103e6043e6

### Development Approach 🚀

the UI should be properly visible

### Deployment Status

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I adhere to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by Puskar-Roy** [comment]
Hey @Sourabh782👋! Thanks for raising this issue and demonstrating your interest in contributing to our project!🚀
    We value your engagement and eagerly anticipate your contributions. Should you wish to get involved, please use the /assignme command to self-assign the issue.
    This issue provides an excellent opportunity for us to enhance our project, and we're excited to have you join us! Please take a moment to review our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) before getting started.
    If you have any questions or need assistance, feel free to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/).❤️

**Comment by Puskar-Roy** [comment]
Hello @Sourabh782! We'd like to inform you that the issue has been resolved and is now closed. We appreciate your understanding and look forward to your continued involvement with our repository!🤗
If you encounter any further issues, please don't hesitate to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/). Thank you for your support!❣️
Happy coding!✨ We hope to see you again soon!❣️
