### ISSUE TITLE
[WEB Improvement] : ENHANCEMENT OF WEBSITE

### ISSUE THREAD

**Issue by ABHISIKTAcommits** [Puskar-Roy/create-my-api#84]
### Quick Description 🛠️

CONTACT US PART IS MISSING.
BACK TO TOP PART IS MISSING.

### Select the open-source program you're contributing to

GSSoC- extd, Hacktoberfest 2024

### Adherence to Code of Conduct

- [X] I adhere to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

PLEASE ASSIGN THIS ISSUE TO ME AND ALSO ADD THE LABELS OF hacktoberfest-accepted and gssoc-extd.

**Comment by Puskar-Roy** [comment]
Hey @ABHISIKTAcommits👋! Thanks for raising this issue and demonstrating your interest in contributing to our project!🚀
    We value your engagement and eagerly anticipate your contributions. Should you wish to get involved, please use the /assignme command to self-assign the issue.
    This issue provides an excellent opportunity for us to enhance our project, and we're excited to have you join us! Please take a moment to review our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) before getting started.
    If you have any questions or need assistance, feel free to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/).❤️

**Comment by syedfardeenjeelani** [comment]
@Puskar-Roy  could you please assign this issue to me

**Comment by Puskar-Roy** [comment]
@syedfardeenjeelani @ABHISIKTAcommits anyone want to continue with this issue?

**Comment by syedfardeenjeelani** [comment]
Yes

**Comment by Puskar-Roy** [comment]
Hello @ABHISIKTAcommits! We'd like to inform you that the issue has been resolved and is now closed. We appreciate your understanding and look forward to your continued involvement with our repository!🤗
If you encounter any further issues, please don't hesitate to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/). Thank you for your support!❣️
Happy coding!✨ We hope to see you again soon!❣️
