### ISSUE TITLE
[ADD API] : CRUD API

### ISSUE THREAD

**Issue by sum1t-here** [Puskar-Roy/create-my-api#86]
### API Summary 📝

Operation | HTTP Method | Endpoint | Description | Example Response
-- | -- | -- | -- | --
Create | POST | /resource | Create a new resource | 201 Created
Read | GET | /resource | Retrieve all resources | 200 OK
Read | GET | /resource/:id | Retrieve a specific resource | 200 OK
Update | PUT/PATCH | /resource/:id | Update a specific resource | 200 OK
Delete | DELETE | /resource/:id | Delete a specific resource | 200 OK

### Development Approach 🚀

# CRUD API Development Approach

## Define API Endpoints
- Identify the resources and actions required for the API.
- Typical actions:
  - **Create**
  - **Read**
  - **Update**
  - **Delete**

## Set Up Express.js
1. Initialize an Express.js server.
2. Set up the routes for each CRUD operation.

## Database Setup
- Use MongoDB (with Mongoose) or another database.
- Define schemas and models for your resources.

## Implement CRUD Operations
- **Create (POST):** Accept data and insert it into the database.
- **Read (GET):** Fetch data (all or specific by ID) from the database.
- **Update (PUT/PATCH):** Modify existing data based on ID.
- **Delete (DELETE):** Remove data from the database based on ID.

## Error Handling
- Ensure proper validation for inputs.
- Handle errors like `404 Not Found` or `500 Server Error`.

### Deployment Status

Yes

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I adhere to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by Puskar-Roy** [comment]
Hey @KishanVyas308, the issue has already been assigned and cannot be assigned to you again. Feel free to work on another issue or create a new one.😥

**Comment by Puskar-Roy** [comment]
@sum1t-here do you want to work in this issue? otherwise i can assign @KishanVyas308

**Comment by sum1t-here** [comment]
Working on it

**Comment by Puskar-Roy** [comment]
Hello @sum1t-here! We'd like to inform you that the issue has been resolved and is now closed. We appreciate your understanding and look forward to your continued involvement with our repository!🤗
If you encounter any further issues, please don't hesitate to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/). Thank you for your support!❣️
Happy coding!✨ We hope to see you again soon!❣️
