### ISSUE TITLE
[Documentation Issue] : Changes in code of conduct

### ISSUE THREAD

**Issue by Sumanth077s** [Puskar-Roy/create-my-api#89]
### Brief Description 📝

Missing Definition for Microaggressions:

While microaggressions are mentioned in the "unacceptable behavior" section, there is no explanation or definition provided. Including a clear definition would help members understand what constitutes a microaggression and why it is harmful.
Lack of Examples for Inclusivity in Communication:

The section on "Inclusivity in Communication" states that members should use inclusive language, but it does not provide specific examples. Adding examples of inclusive vs. exclusive language could help clarify this guideline.
Inconsistent Terminology:

In the "Enforcement Guidelines," the term "Community Impact" is used, but in the main body, the term "Consequence" is used. It would be clearer if consistent terminology is maintained throughout the document to avoid confusion.
No Specific Timeframes for Temporary Bans:

The section on "Temporary Ban" states that it will last for a "specified period of time" but does not provide any guidelines or examples for how long this period might be. Specifying a timeframe or range (e.g., one week to one month) could help in setting clearer expectations.
Lack of Clarity on Reporting Process:

The document does not clearly outline the steps involved in the reporting process for violations of the Code of Conduct. Providing a step-by-step guide on how to report incidents, what information is needed, and what to expect during the investigation would enhance transparency and encourage more individuals to come forward.

### Select the open-source program you are contributing to

Other

### Code of Conduct

- [X] I agree to the [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

**Comment by Puskar-Roy** [comment]
Hey @Sumanth077s👋! Thanks for raising this issue and demonstrating your interest in contributing to our project!🚀
    We value your engagement and eagerly anticipate your contributions. Should you wish to get involved, please use the /assignme command to self-assign the issue.
    This issue provides an excellent opportunity for us to enhance our project, and we're excited to have you join us! Please take a moment to review our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) before getting started.
    If you have any questions or need assistance, feel free to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/).❤️

**Comment by Puskar-Roy** [comment]
Hello @Sumanth077s! We'd like to inform you that the issue has been resolved and is now closed. We appreciate your understanding and look forward to your continued involvement with our repository!🤗
If you encounter any further issues, please don't hesitate to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/). Thank you for your support!❣️
Happy coding!✨ We hope to see you again soon!❣️
