### ISSUE TITLE
Adding scroll progress bar

### ISSUE THREAD

**Issue by AswaniBolisetti** [Puskar-Roy/create-my-api#96]
@Puskar-Roy 
I would like to add scroll progress bar to the website
could you please assign it to me

**Comment by Puskar-Roy** [comment]
Hey @AswaniBolisetti👋! Thanks for raising this issue and demonstrating your interest in contributing to our project!🚀
    We value your engagement and eagerly anticipate your contributions. Should you wish to get involved, please use the /assignme command to self-assign the issue.
    This issue provides an excellent opportunity for us to enhance our project, and we're excited to have you join us! Please take a moment to review our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) before getting started.
    If you have any questions or need assistance, feel free to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/).❤️

**Comment by Puskar-Roy** [comment]
@AswaniBolisetti can u please explain it?

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy like how we have a orange progress bar at the top in our girlScript website which is representing how much the website scrolling

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy If you like, could you please assign it to me

**Comment by Puskar-Roy** [comment]
@AswaniBolisetti ok go for it, but please do not change any major change in UI!

**Comment by AswaniBolisetti** [comment]
@Puskar-Roy could you please add the labels

**Comment by Puskar-Roy** [comment]
Hello @AswaniBolisetti! We'd like to inform you that the issue has been resolved and is now closed. We appreciate your understanding and look forward to your continued involvement with our repository!🤗
If you encounter any further issues, please don't hesitate to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/). Thank you for your support!❣️
Happy coding!✨ We hope to see you again soon!❣️
