### ISSUE TITLE
Enhancement of Footer Component with Code Improvements

### ISSUE THREAD

**Issue by Sumanth077s** [Puskar-Roy/create-my-api#97]
The Footer component in the current implementation requires several enhancements for better maintainability, readability, and overall appearance. Below are the details regarding the improvements made and further suggestions for enhancement:

Improvements Made:

Destructuring Links:
Replaced the repeated Link components with an array of link objects. This change simplifies the code, making it more readable and easier to maintain.

Consistency in Spacing:
Ensured consistent className attributes for the Link components, particularly the spacing classes (me-4 md:me-6), to enhance the overall layout.

Corrected Typo:
Fixed the spelling of "Devloped" to "Developed" in the footer text, ensuring proper language use.

Max Width Correction:
Changed mx-auhref to mx-auto for consistent centering, which was previously a typo.

Removed Unused Classes:
Eliminated unnecessary or redundant classes that did not affect the layout, streamlining the component.

Expected Outcome:
These improvements and suggestions aim to enhance the Footer component's code quality and visual appeal, providing a better user experience and making future maintenance easier.

**Comment by Puskar-Roy** [comment]
Hey @Sumanth077s👋! Thanks for raising this issue and demonstrating your interest in contributing to our project!🚀
    We value your engagement and eagerly anticipate your contributions. Should you wish to get involved, please use the /assignme command to self-assign the issue.
    This issue provides an excellent opportunity for us to enhance our project, and we're excited to have you join us! Please take a moment to review our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) before getting started.
    If you have any questions or need assistance, feel free to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/).❤️

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by Puskar-Roy** [comment]
Hello @Sumanth077s! We'd like to inform you that the issue has been resolved and is now closed. We appreciate your understanding and look forward to your continued involvement with our repository!🤗
If you encounter any further issues, please don't hesitate to reach out to us on [LinkedIn](https://www.linkedin.com/in/puskar-roy/). Thank you for your support!❣️
Happy coding!✨ We hope to see you again soon!❣️
